<?php

return [
    'title' => 'About the AI Image Sharing Website',
    'subtitle' => 'A hub for artistic creations powered by artificial intelligence',

    'purpose_title' => 'Purpose & Mission',
    'purpose_text' => 'Our website was created to build an online community where people can explore, enjoy, and share images generated by artificial intelligence (AI). We aim to make AI artworks more accessible, inspiring, and showcase the beauty of technology fused with art.',

    'source_title' => 'Image Sources',
    'source_text' => 'Images on our site are curated and downloaded from popular AI image-generation platforms across the internet. These images are created by users of those platforms; we only serve as a hub that organizes and re-introduces them for a smoother experience tailored to Vietnamese users.',

    'features_title' => 'Main Features',
    'features' => [
        'Browse images by category or topic',
        'Search images by keywords or description',
        'Like your favorite images',
        'Track views and likes statistics',
    ],

    'users_title' => 'Who It’s For',
    'users_text' => 'This website suits technology art lovers, AI enthusiasts, creative designers, or simply anyone who wants to discover the beauty of AI-generated images.',

    'copyright_title' => 'Copyright Notice',
    'copyright_text' => 'We always strive to credit image sources properly. If you are the owner of any image and wish to request its removal, please contact us for prompt resolution. Alternatively, you can click the report button on the image to submit a report.',

    // Contact
    'contact_title' => 'Contact Us',
    'contact_subtitle' => 'If you have any questions, suggestions, or feedback, don’t hesitate to reach out to us using the information below.',
    'contact_address_label' => 'Address:',
    'contact_email_label' => 'Email:',
    'contact_phone_label' => 'Phone:',

    // Terms of Service
    'tos_title' => 'Terms of Service',
    'tos_subtitle' => 'Please read the terms below carefully before using the website.',
    'tos_accept_title' => '1. Acceptance of Terms',
    'tos_accept_content' => 'By accessing and using our website, you agree to comply with all the terms and conditions outlined in this document. If you do not agree to any part of the terms, please stop using the service.',
    'tos_image_title' => '2. Image Content',
    'tos_image_content' => 'The images on the website are collected from public AI image-generation platforms. We do not own the copyright and only share for reference and entertainment purposes. If you are the content owner and want the image removed, please contact us.',
    'tos_privacy_title' => '3. Privacy',
    'tos_privacy_content' => 'We are committed to protecting your personal information. Data such as emails, search history, etc., will be kept strictly confidential and not shared with third parties.',
    'tos_user_title' => '4. User Responsibilities',
    'tos_user_1' => 'Do not use images from the website for commercial purposes without permission from the original owner.',
    'tos_user_2' => 'Do not upload or share content that violates the law or copyrights.',
    'tos_user_3' => 'Do not engage in destructive behavior, cause system errors, or gain unauthorized access.',
    'tos_change_title' => '5. Changes to Terms',
    'tos_change_content' => 'We reserve the right to update or change these terms at any time. All changes will be posted on this page and take effect immediately.',
    'tos_contact_title' => '6. Contact',
    'tos_contact_content' => 'If you have any questions regarding the Terms of Service, please contact us via email:',

    // Privacy Policy
    'privacy_title' => 'Privacy Policy',
    'privacy_subtitle' => 'We are committed to protecting your data and privacy when using our website.',
    'privacy_collect_title' => '1. Information Collection',
    'privacy_collect_content' => 'We collect certain personal information from users to manage accounts, enhance user experience, and ensure security throughout the service.',
    'privacy_collect_1' => 'Collected data may include full name, email address, phone number, username, and password. We may also collect IP addresses and access behavior for system optimization and analytics purposes.',
    'privacy_collect_2' => 'This information is used for user authentication, personalized experiences, technical support, and to continuously improve service quality and protect user interests.',
    'privacy_collect_3' => 'PhotoAIgen is committed to not selling, renting, or sharing users\' personal information with any third party, except with the user’s consent or when legally required by government authorities.',

    'privacy_use_title' => '2. Purpose of Use',
    'privacy_use_content' => 'User information is collected to enhance the experience and ensure safety while using our services.',
    'privacy_use_1' => 'We use this information to: verify accounts, send account or service-related notifications, provide user support, respond to inquiries, prevent unauthorized access, and deliver updates related to our terms of service.',
    'privacy_use_2' => 'We are committed to protecting your account and personal data. Authentication mechanisms are implemented during login and data processing to prevent hacking, impersonation, and unauthorized access.',
    'privacy_use_3' => 'To enhance security, our system will automatically log out inactive users after a period of time. We also apply encryption and modern authentication standards to safeguard your personal information.',

    'privacy_protect_title' => '3. Data Protection',
    'privacy_protect_content' => 'We are committed to safeguarding users\' personal data through advanced technical and organizational measures.
        All data transmitted between your device and our servers is encrypted using SSL/TLS protocols to ensure secure communication. Our servers are hosted in secure data centers with strict access controls, both physically and digitally, to prevent unauthorized access.
        We implement strong authentication practices including secure password handling, CSRF tokens, XSS protection, and intrusion detection technologies to prevent data breaches and malicious attacks.
        In addition, all login attempts and sensitive operations are logged for auditing and monitoring purposes. In the event of a security vulnerability or intrusion attempt, we employ an immediate incident response protocol to isolate threats, protect users, and restore operations.
        Our security policies and infrastructure are regularly reviewed and updated to meet international best practices and comply with applicable legal requirements.',

    'privacy_share_title' => '4. Information Sharing',
    'privacy_share_content' => 'We **do not share** personal data with any third parties except with your consent or when required by law.',

    'privacy_rights_title' => '5. User Rights',
    'privacy_rights_content' => 'You have the right to:',
    'privacy_rights_1' => 'Request to view, edit, or delete personal information',
    'privacy_rights_2' => 'Unsubscribe from notifications or emails from the system',
    'privacy_rights_footer' => 'Please contact us here to make a request related to your personal data.',

    'privacy_change_title' => '6. Policy Changes',
    'privacy_change_content' => 'This policy may be updated periodically. All changes will be posted on this page and take effect immediately after being published.',

    'privacy_contact_title' => '7. Contact',
    'privacy_contact_content' => 'If you have any questions about the Privacy Policy, please contact us via email:',
];
